name = "silas"
compatibility_date = "2026-08-01"
compatibility_flags = ["nodejs_compat"]
main = ".svelte-kit/cloudflare/_worker.js"
assets = { directory = ".svelte-kit/cloudflare", binding = "ASSETS" }

workers_dev = false
preview_urls = false

[[d1_databases]]
binding = "DB"
database_name = "silas"
database_id = "8b334a16-a196-4f59-9f27-07e05cd10994"
